#!/bin/bash
# =============================================================================
# ZoneWise.AI - Greptile Comprehensive Security & Code Evaluation
# Automated task for Claude Code execution
# Date: 2025-02-09
# Repos: zonewise-desktop, zonewise-web
# =============================================================================

set -euo pipefail

# --- Configuration (set via environment or GitHub Secrets) ---
GREPTILE_API_KEY="${GREPTILE_API_KEY:?ERROR: Set GREPTILE_API_KEY env var}"
GITHUB_TOKEN="${GITHUB_TOKEN:?ERROR: Set GITHUB_TOKEN env var}"
GREPTILE_BASE="https://api.greptile.com/v2"
SESSION_ID="zonewise-security-audit-$(date +%Y%m%d-%H%M%S)"
REPORT_DIR="./greptile-audit-report"
REPORT_FILE="${REPORT_DIR}/zonewise-security-audit-$(date +%Y%m%d).md"

mkdir -p "$REPORT_DIR"

# Repos to audit
REPOS_JSON='[
  {"remote": "github", "repository": "breverdbidder/zonewise-desktop", "branch": "main"},
  {"remote": "github", "repository": "breverdbidder/zonewise-web", "branch": "main"}
]'

# --- Helper: Query Greptile ---
query_greptile() {
  local query="$1"
  local genius="${2:-true}"
  
  echo "  → Querying: ${query:0:80}..." >&2
  
  local response
  response=$(curl -s -w "\n%{http_code}" -X POST "${GREPTILE_BASE}/query" \
    -H "Authorization: Bearer ${GREPTILE_API_KEY}" \
    -H "X-Github-Token: ${GITHUB_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$(jq -n \
      --arg q "$query" \
      --arg sid "$SESSION_ID" \
      --argjson genius "$genius" \
      --argjson repos "$REPOS_JSON" \
      '{
        "messages": [{"id": "user", "content": $q, "role": "user"}],
        "repositories": $repos,
        "sessionId": $sid,
        "stream": false,
        "genius": $genius
      }'
    )" 2>/dev/null)
  
  local http_code
  http_code=$(echo "$response" | tail -n1)
  local body
  body=$(echo "$response" | sed '$d')
  
  if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
    # Extract message and sources from Greptile response
    local message
    message=$(echo "$body" | jq -r '.message // empty' 2>/dev/null)
    if [ -z "$message" ]; then
      message=$(echo "$body" | head -c 5000)
    fi
    
    local sources
    sources=$(echo "$body" | jq -r '.sources[]? | "  - `\(.filepath // "unknown")` (L\(.linestart // "?")-L\(.lineend // "?")): \(.summary // "N/A")"' 2>/dev/null)
    
    echo "$message"
    if [ -n "$sources" ]; then
      echo ""
      echo "**Referenced Files:**"
      echo "$sources"
    fi
  else
    echo "⚠️ API returned HTTP $http_code"
    echo "$body" | jq -r '.error // .message // "Unknown error"' 2>/dev/null || echo "$body"
  fi
}

# --- Verify repos are indexed ---
echo "============================================="
echo "ZoneWise.AI Greptile Security & Code Audit"
echo "Session: $SESSION_ID"
echo "============================================="
echo ""

echo "🔍 Checking repo index status..."
for repo in "breverdbidder/zonewise-desktop" "breverdbidder/zonewise-web"; do
  encoded=$(echo "github:main:${repo}" | python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read().strip(), safe=''))")
  status=$(curl -s -X GET "${GREPTILE_BASE}/repositories/${encoded}" \
    -H "Authorization: Bearer ${GREPTILE_API_KEY}" \
    -H "X-Github-Token: ${GITHUB_TOKEN}" \
    -H "Content-Type: application/json" 2>/dev/null)
  
  repo_status=$(echo "$status" | jq -r '.status // "unknown"' 2>/dev/null || echo "error")
  files=$(echo "$status" | jq -r '.numFiles // "?"' 2>/dev/null || echo "?")
  echo "  ✓ ${repo}: status=${repo_status}, files=${files}"
done
echo ""

# --- Initialize Report ---
cat > "$REPORT_FILE" << 'HEADER'
# ZoneWise.AI — Comprehensive Security & Code Evaluation Report

**Generated by:** Greptile AI Code Analysis  
**Date:** REPORT_DATE  
**Session:** SESSION_ID  
**Repositories:** zonewise-desktop, zonewise-web  
**Assessment Framework:** Security & Value Assessment Protocol (Score 80+=ADOPT, 60-79=EVALUATE, 40-59=CONDITIONAL, <40=REJECT)

---

## Table of Contents

1. [Executive Summary](#1-executive-summary)
2. [Authentication & Authorization](#2-authentication--authorization)
3. [API Security & Input Validation](#3-api-security--input-validation)
4. [Dependency & Supply Chain Security](#4-dependency--supply-chain-security)
5. [Secrets & Credential Management](#5-secrets--credential-management)
6. [Data Handling & Privacy](#6-data-handling--privacy)
7. [Error Handling & Logging](#7-error-handling--logging)
8. [Architecture & Code Quality](#8-architecture--code-quality)
9. [Frontend Security (XSS, CSRF, CSP)](#9-frontend-security)
10. [Performance & Scalability Concerns](#10-performance--scalability)
11. [Test Coverage & CI/CD](#11-test-coverage--cicd)
12. [Critical Findings & Recommendations](#12-critical-findings--recommendations)
13. [Security Score Summary](#13-security-score-summary)

---

HEADER

# Replace placeholders
sed -i "s/REPORT_DATE/$(date '+%B %d, %Y')/g" "$REPORT_FILE"
sed -i "s/SESSION_ID/${SESSION_ID}/g" "$REPORT_FILE"

# --- Define Audit Queries ---
declare -A QUERIES

QUERIES["## 1. Executive Summary"]="Provide a comprehensive executive summary of the zonewise-desktop and zonewise-web codebases. What is the overall architecture? What frameworks, languages, and key dependencies are used? What is the general code quality level? Identify the top 5 most critical areas of concern from a security and maintainability standpoint."

QUERIES["## 2. Authentication & Authorization"]="Analyze all authentication and authorization mechanisms in the codebase. How are users authenticated? Are there any JWT implementations, session management, OAuth flows, or API key handling? Are there any routes or endpoints that lack proper auth guards? Check for hardcoded credentials, default passwords, insecure token storage, missing RBAC, or privilege escalation vulnerabilities. Show specific code locations."

QUERIES["## 3. API Security & Input Validation"]="Examine all API endpoints and data input points. Is there proper input validation and sanitization? Are there SQL injection, NoSQL injection, command injection, or path traversal vulnerabilities? Check for missing rate limiting, CORS misconfigurations, and unsafe deserialization. Show specific vulnerable code locations with file paths and line numbers."

QUERIES["## 4. Dependency & Supply Chain Security"]="Analyze all dependencies in package.json, requirements.txt, or any dependency files. Are there known vulnerable packages (CVEs)? Are dependencies pinned to specific versions or using loose ranges? Are there any abandoned or unmaintained dependencies? Check for typosquatting risks. List any dependencies with known security advisories."

QUERIES["## 5. Secrets & Credential Management"]="Search the entire codebase for hardcoded secrets, API keys, tokens, passwords, connection strings, or any sensitive credentials. Check .env files, config files, and inline code. Are there any secrets committed to git history? Is there a proper secrets management pattern (env vars, vault, etc.)? List every instance found with exact file paths."

QUERIES["## 6. Data Handling & Privacy"]="How is sensitive data handled throughout the codebase? Is there proper encryption at rest and in transit? How is PII (personally identifiable information) processed and stored? Are there any data exposure risks through logs, error messages, or API responses? Check for insecure data serialization or transmission patterns."

QUERIES["## 7. Error Handling & Logging"]="Evaluate error handling patterns across the codebase. Are errors properly caught and handled? Do error messages expose sensitive internal details (stack traces, DB queries, file paths)? Is there structured logging? Are there any unhandled promise rejections or uncaught exceptions? Check for information leakage through verbose error responses."

QUERIES["## 8. Architecture & Code Quality"]="Evaluate the overall code architecture. Is there proper separation of concerns? Are there code smells like massive functions, deep nesting, circular dependencies, or god objects? What design patterns are used? Is the code DRY? Are there proper TypeScript types or is 'any' overused? Assess maintainability score 1-10 with justification."

QUERIES["## 9. Frontend Security (XSS, CSRF, CSP)"]="Analyze the frontend code for security vulnerabilities. Check for XSS (Cross-Site Scripting) risks including dangerouslySetInnerHTML usage, unsanitized user input rendering, and DOM manipulation. Check for CSRF protections, Content Security Policy headers, clickjacking prevention, and secure cookie configuration. Are there any open redirect vulnerabilities?"

QUERIES["## 10. Performance & Scalability Concerns"]="Identify performance bottlenecks and scalability issues. Are there N+1 query problems, memory leaks, unbounded loops, missing pagination, large bundle sizes, or inefficient algorithms? Check for missing caching strategies, unoptimized database queries, and resource-intensive operations that could cause denial of service under load."

QUERIES["## 11. Test Coverage & CI/CD"]="Evaluate the testing infrastructure. What is the approximate test coverage? Are there unit tests, integration tests, and e2e tests? Is there a CI/CD pipeline configured? Are there security scanning tools integrated (SAST, DAST, dependency scanning)? Check for missing test cases in critical security paths like authentication and authorization."

QUERIES["## 12. Critical Findings & Recommendations"]="Based on your analysis of the entire codebase across all previous questions in this session, provide: 1) A prioritized list of the TOP 10 most critical security vulnerabilities found, ranked by severity (CRITICAL/HIGH/MEDIUM/LOW). 2) For each finding, provide: the exact file and line, the vulnerability type, the potential impact, and a specific remediation code fix. 3) Quick wins that can be fixed in under 1 hour."

# --- Run Audit Queries ---
# Order matters for session continuity
ORDERED_SECTIONS=(
  "## 1. Executive Summary"
  "## 2. Authentication & Authorization"
  "## 3. API Security & Input Validation"
  "## 4. Dependency & Supply Chain Security"
  "## 5. Secrets & Credential Management"
  "## 6. Data Handling & Privacy"
  "## 7. Error Handling & Logging"
  "## 8. Architecture & Code Quality"
  "## 9. Frontend Security (XSS, CSRF, CSP)"
  "## 10. Performance & Scalability Concerns"
  "## 11. Test Coverage & CI/CD"
  "## 12. Critical Findings & Recommendations"
)

total=${#ORDERED_SECTIONS[@]}
current=0

for section in "${ORDERED_SECTIONS[@]}"; do
  current=$((current + 1))
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "📋 [${current}/${total}] ${section}"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  
  query="${QUERIES[$section]}"
  result=$(query_greptile "$query")
  
  # Append to report
  echo "" >> "$REPORT_FILE"
  echo "$section" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "$result" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "---" >> "$REPORT_FILE"
  
  # Rate limiting - Greptile may throttle
  echo "  ⏳ Cooling down (10s)..."
  sleep 10
done

# --- Section 13: Security Score ---
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 [FINAL] Generating Security Score..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

score_result=$(query_greptile "Based on your complete analysis of the zonewise-desktop and zonewise-web codebases in this session, generate a final security scorecard. Score each category 0-100: Authentication (weight 20%), Input Validation (15%), Secrets Management (15%), Dependencies (10%), Data Handling (10%), Error Handling (5%), Code Quality (10%), Frontend Security (10%), Testing (5%). Calculate the weighted total score. State the final verdict: 80+=ADOPT, 60-79=EVALUATE, 40-59=CONDITIONAL, <40=REJECT. Format as a clear table.")

echo "" >> "$REPORT_FILE"
echo "## 13. Security Score Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "$score_result" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "*Report generated automatically by Greptile AI analysis on $(date '+%B %d, %Y at %H:%M %Z')*" >> "$REPORT_FILE"

# --- Done ---
echo ""
echo "============================================="
echo "✅ AUDIT COMPLETE"
echo "============================================="
echo "📄 Report: ${REPORT_FILE}"
echo "📊 Session: ${SESSION_ID}"
echo "🔢 Sections: ${total} + scoring"
echo ""
echo "Next steps:"
echo "  1. Review report in ${REPORT_FILE}"
echo "  2. Copy to /mnt/user-data/outputs/ for download"
echo "  3. Store assessment in docs/assessments/ per protocol"
echo ""
